apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-obo.fullname" . }}
  labels:
    app: {{ template "helm-obo.name" . }}
    chart: {{ template "helm-obo.chart" . }}
spec:
  ports:
  - port: {{ .Values.appService.port }}
    targetPort: {{ .Values.appService.targetPort }}
    protocol: {{ .Values.appService.protocol }}
    nodePort: {{ .Values.appService.nodePort }}
  selector:
    app: {{ template "helm-obo.name" . }}
  type: {{ .Values.appService.type }}
