apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-obo.fullname" . }}-mysql
  labels:
    app: {{ template "helm-obo.name" . }}-mysql
    chart: {{ template "helm-obo.chart" . }}
spec:
  ports:
  - port: {{ .Values.dbService.port }}
    targetPort: {{ .Values.dbService.targetPort }}
    protocol: {{ .Values.dbService.protocol }}
  selector:
    app: {{ template "helm-obo.name" . }}-mysql
  type: {{ .Values.dbService.type }}
