apiVersion: apps/v1
kind: Deployment
metadata:
  name: obo
  labels:
    app: obo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: obo
  template:
    metadata:
      labels:
        app: obo
    spec:
      containers:
      - name: obo-container
        image: quoctran08/my_obo:v1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: obo-config-file
              key: DATABASE_URL
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: obo-config-file
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: obo-config-file
              key: DATABASE_PASSWORD
