apiVersion: v1
kind: Service
metadata:
  labels:
    app: obo
  name: obo-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: '30000'
  selector:
    app: obo
  type: NodePort
