apiVersion: v1
kind: Secret
metadata:
  name: obo-config-file
type: Opaque
stringData:
  DATABASE_URL: jdbc:mysql://mysql-service.prd.svc.cluster.local:3306/obo?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  DATABASE_USERNAME: admin
  DATABASE_PASSWORD: '123456'
